### ISSUE TITLE
estimated time for TODOs

### ISSUE THREAD

**Issue by kacole2** [scottbri/PyMAX#3]
Hi Scott. First off, I just wanted to extend a thanks for your work. Great job. Second part was curious to know your timeline for implementation of these two features?
- fully implement the reporting API
- implement all available CRUD API calls

I think after baking these two features, especially the remaining CRUD it will be locked and ready to go. This will lead into a second issue I will open.

**Comment by scottbri** [comment]
I'm looking at the project as free time permits.  Recruiting a little help will help ;-)  As this is my first API client, I'm thinking about whether to just go down the path of wrapping a function around every API call or making the client a little higher level and easier to use.

I suppose, as I put this in writing, implementing all the API calls comes first, and then taking the implementation up a level with some higher level capabilities comes next.  Thoughts?

Do you have any good resources for the "right" way to implement a robust api client that's maintainable over time?

**Comment by kacole2** [comment]
@scottbri this is more of a CLI than an `API Client`. 

I wouldn't worry about wrapping a function around **every** API because that would be way too much time. I would pick the top 10 or 20 that are going to be used the most. After that, you should have a basic boiler plate that if people see this later it should be relatively easy for them to add in those methods.

I'm not sure what higher levels you are talking about, so I can't really give you a direction or advice. :)

As for doing things the "right" way, there is no standard way. The most standard way to do things is to go Prog -> Noun -> Verb -> Adverb or Options

Such as `pyvmax create volume --size 10 --iops 2000` or whatever it would be. As for maintainability, just take care of as many methods/APIs as you can and it should be able to pick up legs if people want to use it. APIs will be added and deprecated over time. Nature of the way things are.

Keep up the good work.

**Comment by scottbri** [comment]
Mwahahaha

I've implemented about 90% of all the API calls at this point.
