### ISSUE TITLE
Documentation for use

### ISSUE THREAD

**Issue by kacole2** [scottbri/PyMAX#4]
I would like to see some additional updates to the docs before adding to the emccode.com page.

Usage should be something like:

```
$ git clone <repo name>
$ python symmREST.py -h
```

Next, I don't have a VMAX array for use but I would like to see some examples of what I can do from your CLI. At this point all I can do is run the `-h` flag. What can I do after supplying the `-url`, `-user` and `-password` flags? What additional arguments should be available? Should those be listed under `optional arguments`?

I'm just looking for some directions on what is available without trolling through code. Thanks!

**Comment by scottbri** [comment]
valid point, and will update

**Comment by kacole2** [comment]
feel free to close this out when the updates have been done

**Comment by scottbri** [comment]
many updates accomplished.  this is nearly a feature complete API client module at this point.  Probably still need to tighten up the examples into a pyvmax CLI... but I'm not actually trying to create a CLI...
